apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: net-github-quay-tekton 
  janus-idp.io/tekton: net-github-quay-tekton
  backstage.io/kubernetes-id: net-github-quay-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: net-github-quay-tekton
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  